CREATE TABLE BOARD(
	IDX NUMBER(6) CONSTRAINT BOARD_IDX_PK PRIMARY KEY,
	TITLE VARCHAR2(50) CONSTRAINT BOARD_TITLE_NN NOT NULL,
	CONTENT VARCHAR2(2000) CONSTRAINT BOARD_CONTENT_NN NOT NULL,
	NAME VARCHAR2(30)
	)
	
CREATE SEQUENCE BOARD_SEQ
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE

select board_seq.nextval from dual;
select * from BOARD;

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '아아아', '아이우에오아이우에오', '쿠냥이');

ALTER TABLE BOARD ADD(FILE_NAME VARCHAR2(300));